services:
  #PHP Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nongdev/inventory-backend:latest
    container_name: inventory_backend
    restart: unless-stopped
    tty: true
    env_file:
      - ./backend/.env
    working_dir: /var/www/html/
    volumes:
        - ./backend/.env:/var/www/html/.env
        - backend_storage:/var/www/html/storage
        - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - app-network
    depends_on:
      - db
    command: >
      sh -c "chown -R www-data:www-data storage bootstrap/cache &&
           chmod -R 775 storage bootstrap/cache &&
           php-fpm"
  

  frontend:
    stdin_open: true
    container_name: inventory_frontend
    image: nongdev/inventory-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/var/www/html/
    networks:
      - app-network

  # FastAPI AI Service
  ai:
    build:
      context: ./inventory_ai
      dockerfile: Dockerfile
    image: nongdev/inventory-ai:latest
    # ports:
    #   - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db


  #Nginx Service
  webserver:
    depends_on:
      - backend
      - frontend
      - ai
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    image: nongdev/inventory-webserver:latest
    container_name: inventory_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "82:82"
    volumes:
      - ./backend/public:/var/www/html:ro 
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: inventory_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_management_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
    # backend_vendor:
    backend_storage:
    mysql_data:
